### ISSUE TITLE
API Versioning not working

### ISSUE THREAD

**Issue by sdrissen** [wit-ai/wit-go#16]
Since wit.ai v2 the wit-go is broken.
I thought `NewClientWithVersion(token, DefaultVersion)` would prevent this, as it calls the API with API versioning. 
But the API may not send an old-fashioned result back.

It will not work with v2, but `DefaultVersion = "20170307"` don't ensure, that this version is used.

I think it is not an issue of wit-go, but with the API.
But to workaround this issue, it is needed to update wit-go to the latest version of the API.

**Comment by plutov** [comment]
Since we use go modules, we can modify the code to support new version.  Clients. who. use old API still may use old git tags.

**Comment by sdrissen** [comment]
Thanks for your kind response.

Could you please elaborate this: 
> Clients. who. use old API still may use old git tags.

Is this a hint, what I need to change, to make it run now?

**Comment by plutov** [comment]
@sdrissen we have to make a decision what version to support, because yes. v1 and v2 have different contracts, so maybe we have to define different types or have wit-go to support only one version at a time, but so it can be imported as `@v2.0.0`

**Comment by plutov** [comment]
@sdrissen new API changes have been pushed, please review.
