### ISSUE TITLE
V2 is incorrectly packaged for Go modules

### ISSUE THREAD

**Issue by nate-anderson** [wit-ai/wit-go#22]
The latest release of this package is a major version (2.0.0) and thus requires a `/v2` suffix on the module path per the [Go modules docs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). It is currently impossible to install the v2.0.0 release of this package via `go get` because of invalid packaging.

**Comment by plutov** [comment]
Thank you, I pushed the fix and bumped the patch version.

**Comment by nate-anderson** [comment]
@plutov thanks for the quick fix!
