### ISSUE TITLE
App creation should return correct struct instead of an App 

### ISSUE THREAD

**Issue by thibaultleouay** [wit-ai/wit-go#8]
According the wit.ai doc [1] when we create an app the response as the following structure 
`{
  "access_token" : "NEW_ACCESS_TOKEN",
  "app_id" : "NEW_APP_ID"
}`

Then instead of returning an empty app the function CreateApp should return this structure instead of an empty App  

[1] https://wit.ai/docs/http/20170307#post__apps_link

**Comment by plutov** [comment]
Fixed it in v1.0.1
