### ISSUE TITLE
QueryEscape dont work with wit.ai api 

### ISSUE THREAD

**Issue by thibaultleouay** [wit-ai/wit-go#9]
Hey, 

I dont know if this issue should be reported here or in the main wit.ai repo. 

But with the golang client when i try to delete a value with a space in it for an intent e.g 

` 
 wit.DeleteEntityValue("intent", "Au revoir")
`
The value is not deleted on wit.ai because of this :   url.QueryEscape(value) 

> Standard QueryEscape call encodes a space with a "+" character.

Also this curl command dont work 
curl -XDELETE 'https://api.wit.ai/entities/intent/values/Au+revoir?v=20170307' 
But this one does 
curl -XDELETE 'https://api.wit.ai/entities/intent/values/Au%20revoir?v=20170307'

**Comment by plutov** [comment]
Thank you for this issue, we should probably change the escape to do URL Escape, I will also look into creating an integration test for it.
